spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
# 是否开启自动配置
rocketmq:
  producter:
    autoconfig: true
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: ${spring.application.name}
    # mq的nameserver地址
    namesrvAddr: localhost:9876
    # 消息最大长度 默认 1024 * 4 (4M)
    maxMessageSize : 4096
    # 发送消息超时时间，默认 3000
    sendMsgTimeOut: 3000
    # 发送消息失败重试次数，默认2
    retryTimesWhenSendFailed: 2
debug: false
