spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/test?user=root&password=&useUnicode=true&characterEncoding=gbk&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
# 是否开启自动配置
rocketmq:
  customer:
    # 是否开启自动配置
    autoconfig: true
    # 发送同一类消息设置为同一个group，保证唯一默认不需要设置，rocketmq会使用ip@pid（pid代表jvm名字）作为唯一标识
    groupName: ${spring.application.name}
    # mq的nameserver地址
    namesrvAddr: localhost:9876
    # 消费者订阅的主题topic和tags（*标识订阅该主题下所有的tags），格式: topic~tag1||tag2||tags3;
    topics: TestTopic~TestTag||HelloTag;HelloTopic~HelloTag;MyTopic~*
    # 消费者线程数据量
    consumeThreadMin: 5
    consumeThreadMax: 32
    # 设置一次消费信心的条数，默认1
    consumeMessageBatchMaxSize: 1
debug: false